services:
  postgres:
    image: postgres:17
    container_name: bookhouse-postgres1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Bookshopbe
    container_name: bookhouse-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./Bookshop
    container_name: bookhouse-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
